machine_name = "pms"

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.provider "virtualbox" do |v|
        v.name = "#{machine_name}"
        v.memory = 2048
        v.cpus = 2
    end

    config.vm.define "#{machine_name}" do |machine|
        machine.vm.network "private_network", ip: "192.168.1.1"
        machine.vm.network "public_network", type: "dhcp" 
        machine.vm.provision "host_shell" do |host_shell|
            host_shell.inline = "scripts/host.sh"
        end

        machine.vm.provision "shell" do |shell|
            shell.path = "scripts/bootstrap.sh"
        end
    end
end
