machine_name = "pma"

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
#        v.customize ['modifyvm', :id, '--natnet1', '192.168.222.5/6']
    end

    config.vm.define "#{machine_name}" do |machine|
        config.vm.network "private_network", ip: "192.168.1.1"
        config.vm.network "public_network", type: "dhcp" 
#        machine.vm.network "private_network", type: "dhcp"
        machine.vm.provision "host_shell" do |host_shell|
            host_shell.inline = "scripts/host.sh"
        end

        machine.vm.provision "shell" do |shell|
            shell.path = "scripts/bootstrap.sh"
        end
    end
end
